# DataSource Config
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/db_activiti7?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver