# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        threads:
          max: 1000
          min-spare: 30
    port: 8082
spring:
    mvc:
      static-path-pattern: /static/**
    profiles:
        active: db
    freemarker:
          suffix: .html
          request-context-attribute: request
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    activiti:
#      database-schema-update: false
      database-schema-update: true
#      database-schema-update: create-drop
#      database-schema-update: drop-create
      check-process-definitions: false
#      historyLevel: none
#      historyLevel: activity
#       默认
      historyLevel: audit
#      historyLevel: full
#      默认关闭，不生成历史表
      db-history-used: true

#mybatis 插件
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bjmashibing.activiti.moduler.*.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: uuid
      id-type: auto
    #      id-type: id_worker
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #    key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1 # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #自定义填充策略接口实现
    #    meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true