# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        threads:
          max: 1000
          min-spare: 30
    port: 8082
spring:
    mvc:
      static-path-pattern: /static/**
    profiles:
        active: db
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss